
v0.6.5:
  functions:
    ✔ Type Descriptor @done(18-07-05 23:22)
    ✔ Basic Type(int, float, bool, string, any, variable-argument) @done(18-07-09 00:21)
    ✔ Primary Expression @done(18-07-07 14:30)
    ☐ Assignment And Return Expression
    ☐ Function Call
    ✔ Koala Code Format(.klc) @done(18-07-07 14:30)
  tests:
    ✔ test/hello.kl @done(18-07-06 20:44)
    ✔ test/error-import.kl @done(18-07-07 14:29)
    ✔ test/simple.kl @done(18-07-09 00:18)
    ☐ test/func-call-return.kl

v0.6.6:
  ☐ TypeDesc is used by compiler, and not for runtime

v0.6.7:
  ☐ quickly access to field and function by using index for second times

expression's values are the right expression' s values

id is a function, it doesn't mean a function call, and it's type is itself,
or a function call's return value's types.

example:
values of foo.bar.hello() are function hello's return values.

questions:
  1. multi-assignment supports function returns multi-values?
  golang errors
  var a, b, c = add(100, 200);
  fmt.Println(a, b, c)
  assignment mismatch: 3 variables but 2 values

  var a, b, c = add(100, 200), 300;
  fmt.Println(a, b, c);
  prog.go:11:9: missing expression in var declaration
  prog.go:11:22: multiple-value add() in single-value context
  prog.go:12:23: undefined: c

* Task
** DONE Expression's value supports multi-valuse
   CLOSED: [2018-07-21 Sat 11:03]
** TODO parse variable and parse variable list combind?

* todo [3/4] [75%]
** CANCELLED tas2k
** TODO task1

** DONE tdodo [3/3]
   CLOSED: [2018-07-21 Sat 12:07]
   - [X] Fix bug
   - [X] Support new feature
   - [X] Release new version

** DONE todo [2/2] [100%]
   CLOSED: [2018-07-21 Sat 12:55]
   - [X] Fix bug
   - [X] Release
